name: exam_architecture_iron
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # network
  dio: ^5.8.0+1

  # state management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1

  # DI
  get_it: ^8.1.0

  # router
  go_router: ^15.1.2

  # xml
  xml2json: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
